### ISSUE TITLE
【CSS】渐变色文字，以及渐变色文字阴影处理

### ISSUE THREAD

**Issue by ScarboroughCoral** [ScarboroughCoral/Notes#117]
## 只针对webkit内核解决方案

```css
.gradient-text{
background-image:-webkit-linear-gradient(#eee,#333);
-webkit-background-clip:text;
-webkit-text-fill-color:transparent;
}
```
以上的方法是利用背景渐变来替代文本颜色，文本颜色透明，背景显示位置仅在文本部分显示。

## 渐变色文字的阴影效果

渐变色文字因为设置了文本填充颜色透明，所以使用`text-shadow`属性进行设置阴影的时候会将原本被文本遮罩的地方的颜色显示出来进而覆盖了背景渐变色。

解决方法是使用`filter:drop-shadow(xxx)`声明进行设置阴影，因为它是设置在文本上层的。
