### ISSUE TITLE
【CSS】设置滚动条样式

### ISSUE THREAD

**Issue by ScarboroughCoral** [ScarboroughCoral/Notes#85]
- Chrome/Edge/Safari，使用`-webkit-scrollbar`
- Firefox，使用新兴的CSS scrollbars API（例如`scrollbar-color`和`scrollbar-width`）

## 最佳实践（同时兼容）
```css
/* The emerging W3C standard
   that is currently Firefox-only */
* {
  scrollbar-width: thin;
  scrollbar-color: blue orange;
}

/* Works on Chrome/Edge/Safari */
*::-webkit-scrollbar {
  width: 12px;
}
*::-webkit-scrollbar-track {
  background: orange;
}
*::-webkit-scrollbar-thumb {
  background-color: blue;
  border-radius: 20px;
  border: 3px solid orange;
}
```

## 详细参考
- [Styling Scrollbars with CSS: The Modern Way to Style Scrollbars](https://alligator.io/css/css-scrollbars/)
