### ISSUE TITLE
【CSS】 :root 伪类选择器

### ISSUE THREAD

**Issue by ScarboroughCoral** [ScarboroughCoral/Notes#87]
## 说明
- `:root`选择给定标准的最高级元素。例如html文档选择`html`，svg选择`svg`。
- 伪类选择器比元素选择器有更高的特异性（优先级）。例如html中，`:root`比`html`优先级要高。

## 实用用法
- 在`:root`内定义全局的CSS自定义属性（CSS变量），通过`var(--name)`来使用。
```css
:root {
  margin: 0;
  padding: 0;
  --primary-color: #0000FF;
  --body-fonts: "Helvetica", "Arial", sans-serif;
  --line-height: 1.5;
}

p {
  color: var(--primary-color);
  font-family: var(--body-fonts);
  line-height: var(--line-height);
}
```
## 详细参考
- [How to Use the CSS :root Pseudo-Class Selector](https://alligator.io/css/root-pseudo-class/)
