### ISSUE TITLE
【CSS】天堂圣杯布局（Holy Grail Layout）CSS Grid 解决方案

### ISSUE THREAD

**Issue by ScarboroughCoral** [ScarboroughCoral/Notes#90]
## html
```html
<div class="container">
  <header>
    <!-- Header content -->
  </header>

  <nav>
    <!-- Navigation -->
  </nav>

  <main>
    <!-- Main content -->
  </main>

  <aside>
    <!-- Sidebar / Ads -->
  </aside>

  <footer>
    <!-- Footer content -->
  </footer>
</div>
```
## css
```css
.container {
  display: grid;

  grid-template-areas:
    "header header header"
    "nav content side"
    "footer footer footer";

  grid-template-columns: 200px 1fr 200px;
  grid-template-rows: auto 1fr auto;
  grid-gap: 10px;

  height: 100vh;
}
header {
  grid-area: header;
}

nav {
  grid-area: nav;
  margin-left: 0.5rem;
}

main {
  grid-area: content;
}

aside {
  grid-area: side;
  margin-right: 0.5rem;
}

footer {
  grid-area: footer;
}
```
## 响应式样式
```css
@media (max-width: 768px) {
  .container {
    grid-template-areas:
      "header"
      "nav"
      "content"
      "side"
      "footer";

    grid-template-columns: 1fr;
    grid-template-rows:
      auto /* Header */
      minmax(75px, auto) /* Nav */
      1fr /* Content */
      minmax(75px, auto) /* Sidebar */
      auto; /* Footer */
  }

  nav, aside {
    margin: 0;
  }
}
```
## flex也可以实现天堂圣杯，grid不是完全替代方案，grid可以结合flex，比如header布局
```css
header {
  grid-area: header;

  display: flex;
  justify-content: space-between;
  align-items: center;
}
```
## 详细参考
- [CSS Grid: Holy Grail Layout](https://alligator.io/css/css-grid-holy-grail-layout/)
